apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-github
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: vote-github.19273e5ee2444e628940.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
        path: /